### ISSUE TITLE
DeprecationWarning: Flags not at the start of the expression '^(?u)[^\\W\\d][-\\w]*$'

### ISSUE THREAD

**Issue by hroncok** [asciidoc-py/asciidoc-py#13]
With Python 3.7, I see a lot of deprecation warnings here:

https://github.com/asciidoc/asciidoc-py3/blob/986f99d743d0b6ddc2014bdc8dcfa991ab9b4863/asciidoc.py#L471

**Comment by elextr** [comment]
I think the `?u` can simply be removed, since its the default in Py3. [See](https://docs.python.org/3/library/re.html#re.ASCII)

**Comment by hroncok** [comment]
Good point, amended.

**Comment by serhiy-storchaka** [comment]
`'^'` at the start of pattern doesn't have any effect, because `re.match()` always matches at the start of the string. It can be removed.

And in Python 3.4+ you can just use `re.fullmatch(NAME_RE, s)`.
