### ISSUE TITLE
Make test suite not rely on files under website/ or doc/

### ISSUE THREAD

**Issue by MasterOdin** [asciidoc-py/asciidoc-py#180]
These files occasionally get updated with new information, links, etc. and it would be ideal to not have to update the test suite at the same time.

**Comment by hoadlck** [comment]
Are you thinking of doing a simple copy of the input files into the tests area, or creating a more targeted test file (by paring down the original file)?

Here are the text input files that do not reside in the `tests` directory:

- ../doc/article.txt
- ../doc/asciidoc.txt
- ../doc/asciidoc.1.txt
- ../doc/asciimath.txt
- ../doc/book.txt
- ../doc/book-multi.txt
- ../doc/latexmath.txt
- ../doc/latexmathml.txt
- ../doc/latex-filter.txt
- ../doc/source-highlight-filter.txt
- ../website/newtables.txt

There is also image content external to the `tests` directory (e.g. `../images`).  But, I assume that this seldom gets updated, so making a copy of it would not be needed.

**Comment by MasterOdin** [comment]
Just a simple copy of the files into the tests directory.
