### ISSUE TITLE
Update SHA checksum for Homebrew installation

### ISSUE THREAD

**Issue by github-throwaway** [asciidoc-py/asciidoc-py#190]
`brew install asciidoc` fails with the following error

`Error: SHA256 mismatch
Expected: 8a6e3ae99785d9325fba0856e04dbe532492af3cb20d49831bfd757166d46c6b
  Actual: 5056c20157349f8dc74f005b6e88ccbf1078c4e26068876f13ca3d1d7d045fe7`

I think the formula for Homebrew needs to be updated?

**Comment by MasterOdin** [comment]
Yup, did not consider the move would break the homebrew formula. Fixed with https://github.com/Homebrew/homebrew-core/pull/71288, will close this issue once that's merged.

**Comment by tonejito** [comment]
I only had to change the checksum, the URL works just fine for me:

- https://github.com/tonejito/homebrew-core/commit/d9a77cc02179601d70d0bc20440a44a9b4e4a00f

**Comment by MasterOdin** [comment]
Yeah, the URL works fine in that it redirects to the new one. However, no reason to not update the URL at the same time in the PR.

**Comment by MasterOdin** [comment]
With above merged, asciidoc-py now properly installs via homebrew again. Sorry about that disruption folks, and thanks for reporting it!
