### ISSUE TITLE
How to install an isolated self-contained asciidoc? (perhaps with pyenv?)

### ISSUE THREAD

**Issue by coolaj86** [asciidoc-py/asciidoc-py#192]
## Goal

Any tips on how I can install a self-contained isolated version of `asciidoc`?

## Backstory

I'm not much into python, but I do know enough to know that anything you do to update, change, or install in the system version of python you will _inevitably_ regret.

I have `pyenv` and typically I use the local option so that when I need to work on python code it can only possibly screw up the version of python for that repository, and not my whole system.

However, I haven't needed to install something that is globally accessible before, so I'm not sure how that works.

I've also learned that anytime I use `brew`, sooner or later it screws up `libssl` and then dozens of things system-wide (curl, ssh, etc) start breaking, so I try to avoid that as well.

**Comment by maximlomans** [comment]
python3 has it all taken care off, i'm sure mac has python3 available, pip comes along...
$ pip install asciidoc  
$ pip freeze 
 ...  dont move; hand me asciidoc or else; i'll unistall yo ass : p
will have its own dir in site_packages, you don't need to build with pyenv setuptools etc pip is willing to help you man, let it

**Comment by MasterOdin** [comment]
I am going to cut a 10.0.0 final release later on today to make things a bit easier to install via PyPI.

**Comment by MasterOdin** [comment]
As stated above, you can install and use asciidoc through pip:

```bash
python3 -m pip install asciidoc
```

This can be run on the entire system, using `--user`, or in virtualenv like any other python package, where `asciidoc` and `a2x` executables will be installed into your python bin folder.

API usage would be:

```python3
import asciidoc
source = '/path/to/input'
outfile = '/path/to/output'

options = self.options[:]
options.append(('--out-file', outfile))
options.append(('--backend', 'html5'))

asciidoc.execute('asciidoc', options, [source])
```
