### ISSUE TITLE
Asciidoc preview in Jupyter Lab ?

### ISSUE THREAD

**Issue by raulcano** [asciidoc-py/asciidoc-py#193]
Hi, is there anyway to have asciidoc previewed in JupyterLab? I have searched everywhere without success and I eneded up here. Hopefully you have some pointers? Thanks in advance!

**Comment by MasterOdin** [comment]
So, my guess here is that you'd need to be able to introduce a new custom cell type to JupyterLab that then runs its input through asciidoc to show output (similar to how the markdown cell input works, I think).

Looks like while [it's maybe possible, it's not well documented](https://discourse.jupyter.org/t/how-to-custom-cell/1280). However, I cannot give you any more advice on this as I've no experience with extending JupyterLab so your best course would probably be to post on their forum board on this.
