### ISSUE TITLE
Test suite: error in call to `convert` when using GraphicsMagick

### ISSUE THREAD

**Issue by marcecj** [asciidoc-py/asciidoc-py#194]
Hi, I'm not sure how much of an issue this actually is, but when running the test suite with GraphicsMagick instead of ImageMagick I get the following errors:
```
[...]
music2png.py: failed command: convert "/var/tmp/portage/app-text/asciidoc-9.1.0/work/asciidoc-9.1.0/tests/data/music1.png" -strip -gravity South -chop 0x75 -trim "/var/tmp/portage/app-text/asciidoc-9.1.0/work/asciidoc-9
.1.0/tests/data/music1.png" 2>/dev/null                                                                                                                                                                                    
music2png.py: failed command: convert "/var/tmp/portage/app-text/asciidoc-9.1.0/work/asciidoc-9.1.0/tests/data/music2.png" -strip -gravity South -chop 0x75 -trim "/var/tmp/portage/app-text/asciidoc-9.1.0/work/asciidoc-9
.1.0/tests/data/music2.png" 2>/dev/null
[...]
music2png.py: failed command: convert "/var/tmp/portage/app-text/asciidoc-9.1.0/work/asciidoc-9.1.0/tests/data/open-block-test__3.png" -strip -gravity South -chop 0x75 -trim "/var/tmp/portage/app-text/asciidoc-9.1.0/wor
k/asciidoc-9.1.0/tests/data/open-block-test__3.png" 2>/dev/null 
[...]
```
I get these messages with versions 9.0.4, 9.0.5, and 9.1.0, but *not* with 9.0.2.

Running the `convert` command directly shows that the error likely stems from the `-trim` option (for whatever reason):
```
# convert "/var/tmp/portage/app-text/asciidoc-9.1.0/work/asciidoc-9.1.0/tests/data/music1.png" -strip -gravity South -chop 0x75 -trim "/var/tmp/portage/app-text/asciidoc-9.1.0/work/asciidoc-9.1.0/tests/data/music1.png"
convert convert: geometry does not contain image (unable to crop image).
# convert "/var/tmp/portage/app-text/asciidoc-9.1.0/work/asciidoc-9.1.0/tests/data/music1.png" -strip -gravity South -chop 0x75 "/var/tmp/portage/app-text/asciidoc-9.1.0/work/asciidoc-9.1.0/tests/data/music1.png"
# echo $?
0
```
I tried googling the error message but didn't really find an explanation I could understand (I wonder whether the message swapped "geometry" and "image" and it's saying that the file does not contain geometry information).  As I said above, though, I'm not sure whether this is *actually* a problem, since the test suite still passes and I can only run the manual commands after the test case generated the image file.  I'm mainly asking just to be safe.

**Comment by elextr** [comment]
The message says that the geometry for the `-trim` does not contain the image, so the `-gravity` and `-chop` which set the geometry have removed the whole image for some reason.  Why and whats changed is outside my pay grade :)

**Comment by MasterOdin** [comment]
Looking into this, it looks like the `-gravity` and `-chop` commands do work as expected (and will apply to the final image), it's just then that `-trim` throws a conniption. Interestingly, reseting the gravity then gets `-trim` to work as expected. I've filed a [bug report](https://sourceforge.net/p/graphicsmagick/bugs/653/) against GM and will see what their maintainers say about it.

For now, I'll open a PR to reset the gravity just to get rid of that pesky warning.

> since the test suite still passes

This is an unfortunate limitation of the testsuite where it does not currently fail on warnings being raised during compilation. Additionally, for that particular test, the outputted documents only include a ref tag to the image (as opposed to embedding the image), so we never do a check on if the generated image is "correct".
