### ISSUE TITLE
Ways to convert to html text from adoc text?

### ISSUE THREAD

**Issue by cytwill** [asciidoc-py/asciidoc-py#196]
Hi,

Are there any API or methods to convert a variable containing asciidoc formatted text to a variable of HTML like text in code (i.e. do not involve reading in and output files)?

Thanks for your help!

**Comment by MasterOdin** [comment]
Sorry for the delay in responding, this message slipped through my inbox.

You can directly call the `asciidoc.execute` method, passing in `StringIO` instances to act as input and output:

```python
infile = io.StringIO('Hello *{author}*')
outfile = io.StringIO()
opts = []
opts.append(('--backend','html4'))
opts.append(('--no-header-footer',None))
opts.append(('--attribute','author=Joe Bloggs'))
opts.append(('--out-file',outfile))
asciidoc.execute(__file__, opts, [infile])
print(outfile.getvalue())
# <p>Hello <strong>Joe Bloggs</strong></p>
```
