### ISSUE TITLE
The `include` macro `lines` behavior don't work

### ISSUE THREAD

**Issue by podsvirov** [asciidoc-py/asciidoc-py#212]
The `lines.txt`:
```txt
Line one
Line two
Line three
```

The `lines.adoc`:
```asciidoc
include::lines.txt[lines=2..3]
```

For `asciidoctor --no-header-footer lines.adoc`:
```html
<div class="paragraph">
<p>Line two
Line three</p>
</div>
```

But for `asciidoc --no-header-footer lines.adoc`:
```html
<div class="paragraph"><p>Line one
Line two
Line three</p></div>
```

**Comment by MasterOdin** [comment]
@podsvirov Does double quoting the `lines` value work for you?

```
include::lines.txt[lines="2..3"]
```

I believe this is an instance where asciidoctor is much more lenient on attribute list parsing than asciidoc.py, which need to incorporate into this library.

**Comment by podsvirov** [comment]
Hm, it's work as expected!

The samples in the [documentation](https://asciidoc-py.github.io/userguide.html#_system_macros) do not say anything about quotation marks. But your advice works - thanks.

Now I doubt if this is a bug. I apologize if I was too demanding.

**Comment by MasterOdin** [comment]
Yeah, this is an unfortunate bit of the breadth of the docs makes it easy to miss little notes. For attribute lists, per the [Attribute List Behavior](https://asciidoc-py.github.io/userguide.html#X21) section, it describes the quoting behavior:

> If the list contains any named or quoted attributes then all string attribute values must be quoted.

Which it is then assumed the reader has seen and conceptualized throughout the rest of the document.

> Now I doubt if this is a bug. I apologize if I was too demanding.

Yeah, I think one avenue would be to improve the docs to always have double quotes around examples. Easy enough to do in this particular case, but for longer term solution, and something that needs to be done anyway, I've opened #213.

Thanks for bringing this up as I had forgotten it was a thing that needed to be done in asciidoc.py 👍

**Comment by podsvirov** [comment]
@MasterOdin, thanks for the detailed answer and quotation from the documentation.

**Comment by MasterOdin** [comment]
I've also made https://github.com/asciidoc-py/asciidoc-py.github.io/commit/cf68cc83fb909a28addb872efd595027df1a926f which improves the examples for lines attribute, which should help also avoid the confusion until a patch for #213 can land.

Thanks again for reporting!
