### ISSUE TITLE
Failure to build manpage from Japanes and Korean translations

### ISSUE THREAD

**Issue by pbrezina** [asciidoc-py/asciidoc-py#216]
Hi, I am a developer of authselect. We use asciidoc to build manual pages. Recently, we have troubles with building Japanese and Korean translations but I was unable to find the root cause. Can you please help me to find what needs to be fixed?

* [translations.log](https://github.com/asciidoc-py/asciidoc-py/files/7474545/translations.log) - failed commands and translations
* [src.tar.gz](https://github.com/asciidoc-py/asciidoc-py/files/7474561/src.tar.gz) translated documents

Original documents can be found [here](https://github.com/authselect/authselect/tree/master/src/man).

**Comment by MasterOdin** [comment]
What version of asciidoc are you using? What version of asciidoc was last working for you?

**Comment by pbrezina** [comment]
```
[pbrezina ~]$ a2x --version
a2x 9.1.0
[pbrezina ~]$ rpm -q asciidoc
asciidoc-9.1.0-1.fc34.noarch
```

I can't tell the latest functional version. Usually, when translated manpages don't build, I am able to quickly identify the problem and update strings. Here, I can't tell what the problem is, translations look correct to me.

**Comment by pbrezina** [comment]
Nevermind, I managed to find and fix the issue in translations.

There was missing dot before section name in code block and missing space after manpage name and title separator.
