### ISSUE TITLE
api.py Fails in Main

### ISSUE THREAD

**Issue by tbpassin** [asciidoc-py/asciidoc-py#224]
_api.py_ in the Main branch, which I think is the same as gets installed by a pip-install, fails to complete when called by a bare-bones program.  There are several problems that are easy to fix, all in _AsciiDocAPI_:

1.  Line 61:
```
self.messages = self.asciidoc.messages[:]
       # self.asciidoc does not exist: use asciidoc.messages[:] instead
```
2. Line 57:
```
asciidoc.execute(self.cmd, opts.values, args)
       # self.cmd does not exist.  It is required by the method call, but is not
       # actually used. So the argument needs to be present but its value
       # does not matter (at least until some future revision).
       # To fix, initialize self.cmd to None or '' during __init__().
```

I could put in a PR for these changes, but I thought there should be some discussion, since I am not aware of the reasons why there is supposed to be a _self.cmd_, and why _self.asciidoc_ is used.  I can see from the _init()_ that there was an idea to be able to call _asciidoc_ from some other location, but that argument is also never used.  If it will never be used, I think it would be better removed even though it is not actually harmful since it has a default `None` value.

Also, it looks like there was a plan to use the _self.cmd_ argument at some future time.  So there could be some discussion as to whether `None` or '' would be acceptable in the future, or whether some other value or object should be passed so that code written today will continue to work later on.

**Comment by tbpassin** [comment]
It is possible to get the existing api.py file to work with a little monkey patching.  You have to give up getting error messages from asciidoc.py, so far as I can see.  Here's a working example -

```
import io
import os
import webbrowser

from asciidoc import AsciiDocAPI
from asciidoc.api import Options

text='''.Test Page
This is a *test*.
'''

def new_init(self, asciidoc_py=None):
    self.options = Options()  # should have been imported by AsciiDocAPI
    self.attributes = {}
    self.messages = ['AsciiDocError']  # at least we won't crash on an error
    self.asciidoc= self  # AsciiDocAPI doesn't have an asciidoc attribute
    self.cmd = ''

AsciiDocAPI.__init__ = new_init
processor = AsciiDocAPI()

infile = io.StringIO(text)
outfile = io.StringIO()

processor.execute(infile, outfile, backend='html5')
result=outfile.getvalue()

if result:
    path = os.path.expanduser(r'~\Temp\asciidoc.html')
    with open(path,'w') as f:
        f.write(result)
    webbrowser.open_new_tab(path)
else:
    print('.... no output')

```

**Comment by MasterOdin** [comment]
This is a bug, and the missing `self` references are a result of the partial move of the code from 9.x where it was totally standalone to 10.x where it's more integrated. From that `self.cmd` should be replaced with the string `"asciidoc"` and `self.asciidoc.messages` should be changed to `asciidoc.messages` as you indicated. Let me know if you'd like to make a PR with these changes.

**Comment by tbpassin** [comment]
Thanks.  I thought it looked like a work in progress, not quite complete. OK, I'Il do a PR shortly.

I'd also suggest exposing the VERSION attribute in asciidoc.__init__.py instead of having it in asciidoc.py.

**Comment by MasterOdin** [comment]
I'd recommend using the `__metadata__.py.__version__` value instead of the `VERSION` constant in asciidoc.py.
