### ISSUE TITLE
Python instalation places files outside of package scope

### ISSUE THREAD

**Issue by alerque** [asciidoc-py/asciidoc-py#241]
The Python part of the installation is (as of 10.1.2) now placing some files that don't belong to it. Most of it's stuff is ending up in `/usr/lib/python3.10/site-packages/asciidoc` which is correct, but there are also things being placed in `/usr/lib/python3.10/site-packages/tests/` which isn't scoped to this package.

**Comment by MasterOdin** [comment]
Thanks for reporting. Fixed in 8670c80a843c0420e7a8807ba3559f3355a5c0ad.
