### ISSUE TITLE
Option --verbose does not work

### ISSUE THREAD

**Issue by 72757373656c6c** [asciidoc-py/asciidoc-py#251]
### Summary

In the previous version of asciidoc (python 2), when the option `--verbose` is used, many helpful messages are generated. In the current version of asciidoc (python 3), no messages are generated. The exact same command is used.

#### Version of asciidoc when `--verbose` worked

```
===> asciidoc --version
asciidoc 8.6.9
```

#### Snippet of `--version`
```
===> asciidoc --verbose --backend=html5 FILE
asciidoc: reading: /etc/asciidoc/asciidoc.conf
asciidoc: reading: ...
asciidoc: reading: ...
asciidoc: include: ...
asciidoc: FILE line 3: reading: ...
asccidoc: reading: /etc/asciidoc/html5.conf
...
```

#### Current version of asciidoc
```
===> asciidoc --version
asciidoc 10.1.4
```

**Comment by MasterOdin** [comment]
Thanks for reporting this, I've confirmed the bug, and will have a fix out for this tomorrow.
