### ISSUE TITLE
PEP 8 fixes and formatting

### ISSUE THREAD

**Issue by adam820** [asciidoc-py/asciidoc-py#3]
Hello! I was taking a look at this project _(specifically @MasterOdin 's fork/Pull Request #2 since it seems there's going to be incoming changes)_ as I, and many others, are interested in the state of Asciidoc for Python 3. One thing I noticed is some rather inconsistent spacing between classes/functions and other PEP 8-related formatting quirks.

I would be happy to go through and make all of those tedious adjustments and send a PR, but I wanted to check that it's something that may be wanted before I get neck deep in the code doing so (or in case I missed some intentional reasoning such as compact source code).

If this is not desired, feel free to close this issue!

**Comment by elextr** [comment]
@adam820 the base code of Asciidoc is pretty old, and may even pre-date PEP-8, thats the most likely reason.

It would be nice to update it, but I don't think its a good idea just now, there are a lot of changes happening, and adding a lot of commit noise just for formatting is likely to get in the way.  Better to hold off until it stabilises a bit.

Will leave this open as a reminder.

**Comment by MasterOdin** [comment]
[flake8](http://flake8.pycqa.org/en/latest/) should also be hooked up in CI to enforce these standards going forward as well after the initial bunch batch of pep8 formatting is done. Or could just move to using [black](https://github.com/ambv/black).

**Comment by adam820** [comment]
I started going through and doing some passes on my own fork ([over here](https://github.com/adam820/asciidoc3/tree/pep8-formatting)) anyway for myself, just to put some eyeballs on the code. I'm going to try and keep it level with what @MasterOdin is doing on their fork; when/if you want it pulled back, ping me and I can PR.

**Comment by MasterOdin** [comment]
@adam820 It's probably worth making a PR for your style changes now. There aren't any code changes in the wings to end up with merge conflicts (though maybe some on your end).

**Comment by adam820** [comment]
Okay, I'll see about getting that going in the next few days.

**Comment by MasterOdin** [comment]
Yeah, that can be moved to the top. It was part of [this whole block](https://github.com/asciidoc/asciidoc/blob/master/asciidoc.py#L380-L474) in the original that I just removed the else branch as it'd never happen without really looking too closely at the contents of either.
