### ISSUE TITLE
Replace use of optparse and getopt with argparse

### ISSUE THREAD

**Issue by MasterOdin** [asciidoc-py/asciidoc-py#4]
Right now, asciidoc uses optparse (a depreciated module) in two places and getopt in all others. It might be preferable to replace usage of both of these with argparse which would allow for much cleaner and shorter implementation of the command line arguments for the code as opposed to these two older formats.

**Comment by elextr** [comment]
Good idea, but it should be a separate pull request.  Also any other deprecated modules (vague memories of MD5 being refactored).

**Comment by MasterOdin** [comment]
Yeah, that was my plan as the current PR is definitely large enough, no reason to do more in it. I did migrate tests/testasciidoc.py as that was the primary thing cli I was using in my testing, and can revert to use the old getopt setup if so wanted.

**Comment by elextr** [comment]
So long as the deprecated module is still available in latest Python so original code still works, then its probably better to keep all the CLI changes in one "remove deprecated CLI module" PR.
