### ISSUE TITLE
Chapter: "Quoted Text"

### ISSUE THREAD

**Issue by GSebastian-Adil** [asciidoc-py/asciidoc-py#46]
When I read the "Quoted Text" Chapter of "Asciidoc User Guide", I found some ponctuation in the description are not in place (and may be I am wrong), So I tried to rewrite this part to express my Opinion.

Thanks

[Quoted_Text.txt](https://github.com/asciidoc/asciidoc-py3/files/2566190/Quoted_Text.txt)

**Comment by elextr** [comment]
These items are showing examples of the markup that is being discussed by the text, they are not punctuation they are markup, so it is intentional and should not be removed.
