### ISSUE TITLE
Replace testasciidoc.py "positional arguments" with flags?

### ISSUE THREAD

**Issue by MasterOdin** [asciidoc-py/asciidoc-py#6]
Here is the usage screen for tests/testasciidoc.py:
```
./tests/testasciidoc.py --help                                                                                                                           [21:43:54]
illegal command options

Usage: testasciidoc.py [OPTIONS] COMMAND

Run AsciiDoc conformance tests specified in configuration FILE.

Commands:
  list                          List tests
  run [NUMBER] [BACKEND]        Execute tests
  update [NUMBER] [BACKEND]     Regenerate and update test data

Options:
  -f, --conf-file=CONF_FILE
        Use configuration file CONF_FILE (default configuration file is
        testasciidoc.conf in testasciidoc.py directory)
  --force
        Update all test data overwriting existing data
```

Based on this, I would expect that usage would be that I can specify a test number as well as a backend for that number. It's not obvious that you can pass an integer (for NUMBER) or a string (for BACKEND) or both and the order doesn't matter. These are loosely positional arguments, but is not obvious in how that is, unless you look at the arg parsing code.

Would it make sense to change it to be that `testasciidoc.py update|run [--number NUMBER] [--backend BACKEND]`. This allows a more straightforward usage model (that can be explained concisely in a usage string). Can make it so the flags are either `--number` or `-n`, and `--backend` or `-b`.

**Comment by elextr** [comment]
Certainly would make it easier to use.  I suspect very few people actually use the tests anyway, so they are pretty much only developer tests, but any improvement is worthwhile.
